# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/packages/app/bot/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
      directory: "/packages/lib/google-docs"
      schedule:
        interval: "weekly"
  - package-ecosystem: "npm"
      directory: "/packages/lib/pg-utils"
      schedule:
        interval: "weekly"
  - package-ecosystem: "npm"
      directory: "/packages/lib/timetable"
      schedule:
        interval: "weekly"
  - package-ecosystem: "npm"
      directory: "/packages/lib/universal-db-sync"
      schedule:
        interval: "weekly"
  - package-ecosystem: "npm"
      directory: "/packages/lib/web"
      schedule:
        interval: "weekly"
  - package-ecosystem: "npm"
      directory: "/packages/app/yandex-afisha"
      schedule:
        interval: "weekly"
  - package-ecosystem: "github-actions"
    # Workflow files stored in the
    # default location of `.github/workflows`
    directory: "/"
    schedule:
      interval: "weekly"
