version: '2.1'
services:
  cult_bot_test:
    image: "postgres:12"
    restart: always
    command: -c fsync=off
    environment:
      POSTGRES_ROOT_PASSWORD: root
      POSTGRES_DATABASE: cult-test
      POSTGRES_USER: cult-test
      POSTGRES_PASSWORD: cult-test
    ports:
      - "5434:5432"
    volumes:
        - ./init.sql:/docker-entrypoint-initdb.d/init.sql
