// eslint-disable-next-line @typescript-eslint/triple-slash-reference
/// <reference path="../../@types/tinkoff.d.ts" />
import Head from 'next/head'
import styles from '@/src/styles/Home.module.css'
import { PaymentForm } from '@/src/components/forms/payment/payment-form'
import React, { FormEvent } from 'react'

import { GetServerSideProps, GetServerSidePropsContext } from 'next'
import { ParsedUrlQuery } from 'querystring'
import { CreatePaymentResponse } from '@culthub/interfaces'
import Script from 'next/script'
import { botApi } from '@/src/api-client/bot-api-client'

export const getServerSideProps: GetServerSideProps = async (context: GetServerSidePropsContext<ParsedUrlQuery>) => {
    const token = context?.params?.['paytoken']
    if (typeof token === 'string') {
        const data: CreatePaymentResponse = await botApi.apiCreatePaymentByToken(token)
        return {
            props: data
        }
    }
    return {
        notFound: true,
    }
}

export default function Pay(props: CreatePaymentResponse): JSX.Element {
    function handleSubmit(e: FormEvent) {
        e.preventDefault()
        pay(e.target)
    }

    return (
        <>
            <Script src="https://securepay.tinkoff.ru/html/payForm/js/tinkoff_v2.js" strategy="beforeInteractive"/>
            <div className={styles.container}>
                <Head>
                    <title>Оплата подписки</title>
                    <meta name="description" content="Generated by create next app"/>
                    <link rel="icon" href="/favicon.ico"/>
                </Head>

                <main className={styles.main}>
                    <PaymentForm onPay={(e) => handleSubmit(e)} details={props}/>
                </main>

                <footer className={styles.footer}>
                    ООО «Культхаб»
                </footer>
            </div>
        </>
    )
}
