CREATE TABLE cb_tags (
	id int NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	category varchar NOT NULL,
	name varchar NOT NULL,
	CONSTRAINT cb_tag_pk PRIMARY KEY (id),
    CONSTRAINT cb_tag_name_category UNIQUE (category, name)
);

CREATE TABLE cb_events_to_tags (
	id int NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	event_id int NOT NULL,
	tag_id int NOT NULL,
	CONSTRAINT cb_events_to_tag_pk PRIMARY KEY (id),
    CONSTRAINT cb_events_to_tag_event_id_fk FOREIGN KEY (event_id) REFERENCES cb_events(id) ON DELETE CASCADE ON UPDATE cascade,
    CONSTRAINT cb_events_to_tag_tag_id_fk FOREIGN KEY (tag_id) REFERENCES cb_tags(id) ON DELETE CASCADE ON UPDATE CASCADE
);
