CREATE TABLE cb_events (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    title VARCHAR NOT null,
    category VARCHAR NOT null,
    subcategory VARCHAR NOT null,
    place VARCHAR NOT null,
    address VARCHAR NOT null,
    timetable VARCHAR NOT null,
    duration VARCHAR NOT null,
    price VARCHAR NOT null,
    notes VARCHAR NOT null,
    description VARCHAR NOT null,
    url VARCHAR NOT null,
    tag_level_1 VARCHAR NOT null,
    tag_level_2 VARCHAR NOT null,
    tag_level_3 VARCHAR NOT null,
    rating INT NOT null,
    reviewer VARCHAR NOT null
);

CREATE UNIQUE INDEX cb_events_category_idx ON cb_events (category,title);
CREATE INDEX cb_events_rating_idx ON cb_events (category, rating);