ALTER TABLE cb_events ADD CONSTRAINT cb_events_pk PRIMARY KEY (id);

CREATE TABLE cb_time_intervals (
	id int NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	event_id int NOT NULL,
	time_from timestamp with time zone NOT NULL,
	time_to timestamp with time zone NULL,
	CONSTRAINT cb_time_intervals_pk PRIMARY KEY (id),
	CONSTRAINT cb_time_intervals_un UNIQUE (event_id,time_from,time_to),
	CONSTRAINT cb_time_intervals_fk FOREIGN KEY (event_id) REFERENCES cb_events(id) ON DELETE CASCADE ON UPDATE CASCADE
);

-- Column comments

COMMENT ON COLUMN cb_time_intervals.time_from IS 'including interval';
COMMENT ON COLUMN cb_time_intervals.time_to IS 'excluding interval';

ALTER TABLE cb_events ADD is_anytime bool NOT NULL DEFAULT false;
