ALTER TABLE cb_users DROP COLUMN IF EXISTS chat_id;
ALTER TABLE cb_users ADD COLUMN IF NOT EXISTS blocked_at timestamptz NULL DEFAULT NULL;
ALTER TABLE cb_users ADD COLUMN IF NOT EXISTS events_liked _int8 NOT NULL DEFAULT '{}'::int8[];
ALTER TABLE cb_users ADD COLUMN IF NOT EXISTS events_disliked _int8 NOT NULL DEFAULT '{}'::int8[];
ALTER TABLE cb_users ADD COLUMN IF NOT EXISTS events_favorite _int8 NOT NULL DEFAULT '{}'::int8[];
ALTER TABLE cb_users ADD COLUMN IF NOT EXISTS clicks int8 NOT NULL DEFAULT 0;

ALTER TABLE cb_events ADD COLUMN IF NOT EXISTS likes int8 NOT NULL DEFAULT 0;
ALTER TABLE cb_events ADD COLUMN IF NOT EXISTS dislikes int8 NOT NULL DEFAULT 0;
ALTER TABLE cb_events ADD COLUMN IF NOT EXISTS likes_fake int8 NOT NULL DEFAULT 0;
ALTER TABLE cb_events ADD COLUMN IF NOT EXISTS dislikes_fake int8 NOT NULL DEFAULT 0;
ALTER TABLE cb_events_snapshot DROP COLUMN IF EXISTS order_rnd;