version: '2.1'
services:
  cult_bot:
    image: "postgres:12"
    restart: always
    environment:
      POSTGRES_ROOT_PASSWORD: root
      POSTGRES_DATABASE: cult
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: cult
    ports:
      - "5433:5432"
    volumes:

      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  cult_bot_test:
    image: "postgres:12"
    restart: always
    command: -c fsync=off
    environment:
      POSTGRES_ROOT_PASSWORD: root
      POSTGRES_DATABASE: cult-test
      POSTGRES_USER: cult-test
      POSTGRES_PASSWORD: cult-test
    ports:
      - "5434:5432"
    volumes:
        - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis
    ports:
      - "6380:6379"
