import Head from 'next/head'
import GoogleMapReact from 'google-map-react';
import { GetStaticProps, InferGetStaticPropsType } from 'next'
import { withLayout } from '@/src/layout/Layout';
import { botApi } from '@/src/api-client/bot-api-client';
import { Exhibition } from '@culthub/interfaces/typings/api/web';
import { appConfig } from '../lib/app-config';
import MapMarker from '@/src/components/map-marker/map-marker';
import { useContext } from 'react';
import { AppContext } from '@/src/context/app.context';

export const getStaticProps: GetStaticProps = async () => {
    const {exhibitions} = await botApi.apiGetExhibitions()
    return {
        props: {
            exhibitions,
            apiKey: appConfig.GOOGLE_MAPS_API_KEY
        }
    }
}

function Home({exhibitions, apiKey}: InferGetStaticPropsType<typeof getStaticProps>): JSX.Element {

    const { selectMapItem, mapItemSelectedId } = useContext(AppContext)

    return (
        <main>
            <Head>
                <title>Культхаб - выставки</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <div style={{height: '100vh', width: '100%'}}>
                <GoogleMapReact
                    bootstrapURLKeys={{key: apiKey}}
                    defaultCenter={
                        {
                            lat: 59.716008,
                            lng: 30.395617,
                        }
                    }
                    defaultZoom={11}
                >
                    {exhibitions.map((e: Exhibition) =>
                        <MapMarker lat={e.lng} lng={e.lat} id={e.id}
                                   onSelected={selectMapItem}
                        >
                            {e.title}
                        </MapMarker>)}
                </GoogleMapReact>
            </div>
            <div>details of {mapItemSelectedId}</div>

        </main>
    )
}

export default withLayout(Home)