import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import { GetStaticProps, InferGetStaticPropsType } from 'next'
import { appConfig } from '@/src/lib/app-config'

export const getStaticProps: GetStaticProps = async () => {
    return {
        props: {
            botName: appConfig.TELEGRAM_BOT_NAME
        }
    }
}

export default function Home({botName}: InferGetStaticPropsType<typeof getStaticProps>): JSX.Element {

    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <main className={styles.main}>
                <div>
                    <Image src="/logo.svg" alt="Logo" width={150} height={150}/>
                </div>
                <div>
                    <Link href={`tg://resolve?domain=${botName}`} passHref={true}>
                        <button>Перейти в бот @{`${botName}`}</button>
                    </Link>
                </div>
            </main>

            <footer className={styles.footer}>
                <a
                    href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                    target="_blank"
                    rel="noopener noreferrer"
                >
                    Powered by{' '}
                    <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16}/>
          </span>
                </a>
            </footer>
        </div>
    )
}
