import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.scss'
import Link from 'next/link'
import { GetStaticProps, InferGetStaticPropsType } from 'next'
import { appConfig } from '@/src/lib/app-config'
import { Layout, withLayout } from '@/src/layout/Layout';

export const getStaticProps: GetStaticProps = async () => {
    return {
        props: {
            botName: appConfig.TELEGRAM_BOT_NAME
        }
    }
}
function Home({botName}: InferGetStaticPropsType<typeof getStaticProps>): JSX.Element {

    return (
        <div className={styles.container}>
            <Head>
                <title>Культхаб</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <main className={styles.main}>
                <div>
                    <Image src="/logo.svg" alt="Logo" width={150} height={150}/>
                </div>
                <div>
                    <Link href={`tg://resolve?domain=${botName}`} passHref={true}>
                        <button>Перейти в бот @{`${botName}`}</button>
                    </Link>
                </div>
            </main>
        </div>
    )
}

export default withLayout(Home)