name: auto-merge

on:
  pull_request_target:
    types: [assigned, opened, synchronize, reopened]

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ahmadnassri/action-dependabot-auto-merge@v2.3.1
        with:
          target: minor
          github-token: ${{ secrets.AUTO_MERGE_TOKEN }}