name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_ROOT_PASSWORD: root
          POSTGRES_DATABASE: cult-test
          POSTGRES_USER: cult-test
          POSTGRES_PASSWORD: cult-test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5434:5432

    env:
      DATABASE_URL: postgres://cult-test:cult-test@localhost:5434/cult-test
      DATABASE_SSL: no

    steps:
      - uses: actions/checkout@v2
      - run: yarn install --immutable --immutable-cache
      - run: yarn build
        env:
          CI: true
      - run: yarn bot:db:up-test
      - run: yarn test
